name: Build on GitHub Actions and Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Podman image
        run: podman build -t ${{ secrets.AWS_REGISTRY_URL }}/poc-demo-app:latest .

      - name: Authenticate with Amazon ECR
        run: |
          ECR_TOKEN=$(aws ecr get-login-password --region ${{ secrets.AWS_REGION }})
          echo $ECR_TOKEN | podman login --username AWS --password-stdin ${{ secrets.AWS_REGISTRY_URL }}

      - name: Push Podman image to Amazon ECR
        run: podman push ${{ secrets.AWS_REGISTRY_URL }}/poc-demo-app:latest

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            # Additional deployment steps here
            podman stop poc-demo-app
            podman rm poc-demo-app
            podman pull ${{ secrets.AWS_REGISTRY_URL }}/poc-demo-app:latest
            podman run -d --name poc-demo-app -p 8081:8081 ${{ secrets.AWS_REGISTRY_URL }}/poc-demo-app:latest
